# Generated by Django 5.2.7 on 2025-10-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_inventorychange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorychange',
            name='new_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorychange',
            name='old_quantity',
            field=models.IntegerField(),
        ),
    ]
